
	-- -- This is a List of Units that need to be created or finished --

	-- ------------------------------------------------------------------------------------
	-- 								-- UEF --
	-- ------------------------------------------------------------------------------------
	
	-- KES 0304	T4 Support Dreadnought							(Poseidon Class)	-- rebalanced, was unable to fix Special Weapon
	-- KEL 0401	T4 Super Heavy Bombardment Tank					(Rat)
	-- KEL 0406	T4 Super Heavy Armored Hovercraft				(Murena)
	-- KEL 0407	T4 Heavy Tank									(Devastator)
	-- KEA 0401	T4 Gunship										(Airboy)
	-- KEL 0404	T4 Assault Vehicle								(Fatboy II)
	-- KEL 0402	T4 Assault Bot									(Mastodon)
	-- KEL 0405	T4 Assault Bot									(King Kriptor)
	-- KEL 0308	T3 Nuclear Cannon								(Nuker)
	-- KEA 0301	T3 Nuclear Bomber								(B-52 Stratofottress)
	-- KEL 0302	T3 Mobile Heavy Cannon							(Pakwagen)
	-- KEL 0305	T3 Mobile Combined Defense Platform				(Bastion)
	-- KEB 2303	T3 Missile Point Defense						(Fog launcher)
	-- KEL 0301	T3 Main Battle Tank								(Jerus)
	-- KEL 0304	T3 MLRS											(Scorcher)
	-- KEB 2302	T3 Intercontinental Ballistic Missile Launcher	(V6 Rocket Installation)
	-- KEL 0307	T3 Hybrid Sniper Missile Launcher				(Artemis)
	-- KEB 2301	T3 Heavy Naval Artillery Bunker					(Naval Cannon)
	-- KES 0302	T3 Heavy Destroyer								(Iwojima Class)
	-- KES 0401	T3 Heavy Cruiser								(Guada Class)
	-- -- KEB 2304	T3 Heavy Anti-Air SAM Launcher					(Thor)	-- Rebalance - Cut Content
	-- KEL 0306	T3 Heavy Amphibious Tank						(Carden)
	-- KEL 0303	T3 Heavy AA Tank								(VVhirIwind)
	-- KES 0301	T3 Dreadnought									(Everest Class)
	-- KEB 2305	T3 Close-In-Weapon-System						(Kashtan)
	-- KES 0305	T3 Battlecarrier								(H-48 Olympus Class)
	-- KES 0201	T2 Tech 2 Early Battleship						(Beirut Class)
	-- KEB 2201	T2 Point Defense								(Pack Gun)
	-- KEB 2202	T2 Mortar Installation							(Dwarf Star)
	-- KEL 0203	T2 Mobile Intel Generator						(Field Scanner)
	-- KEL 0201	T2 Mobile APC									(Paddur)	-- Rebalance
	-- -- KEL 0205	T2 HeavyTankUP									(M551 Sheridan MK2) - Cut Content
	-- KEL 0202	T2 Heavy Tank Destroyer							(Pillarf85)
	-- KEL 0204	T2 Heavy Beam Tank								(Crossbow)
	-- -- KEL 0101	Tl HeavyTank									(M551 Sheridan) - Cut Content
	-- KEA 0101	Tl Gunship										(Blackfish)
	
	-- ------------------------------------------------------------------------------------
	-- 								-- Aeon --
	-- ------------------------------------------------------------------------------------
	
	-- KAS 0304	T4 Support Dreadnought							(TODO)
	-- KAL 0401	T4 Super Heavy Shield Disruptor					(TODO)
	-- -- KAL 0406	T4 Super Heavy Armored Hovercraft				(N/A)
	-- KAL 0407	T4 Mobile Tank									(Slim Boy)	-- Rebalance
	-- KAA 0401	T4 Gunship										(HMP Restorator)
	-- -- KAL 0404	T4 Assault Vehicle								(N/A)
	-- -- KAL 0402	T4 Assault Bot									(N/A)
	-- KAL 0402	T4 Assault Bot									(Colossus)	-- Rebalance
	-- KAL 0308	T3 Nuclear Cannon								(TODO)
	-- KAA 0301	T3 Nuclear Bomber								(TODO)
	-- KAL 0302	T3 Mobile Heavy Cannon							(TODO)
	-- KAL 0305	T3 Mobile Combined Defense Platform				(TODO)
	-- KAB 2303	T3 Acid Point Defense						(TODO)
	-- KAL 0301	T3 Main Battle Tank								(Jarvis)
	-- KAL 0304	T3 MLRS											(Insanity)
	-- KAB 2302	T3 Intercontinental Ballistic Missile Launcher	(TODO)
	-- -- KAL 0307	T3 Hybrid Sniper Missile Launcher				(N/A)
	-- KAB 2301	T3 Heavy Naval Artillery Bunker					(Elea)
	-- KAS 0302	T3 Heavy Destroyer								(Infiltrator Class)
	-- -- KAS 0401	T3 Heavy Cruiser								(N/A)
	-- -- KAB 2304	T3 Heavy Anti-Air SAM Launcher					(N/A) - Cut Content
	-- KAL 0306	T3 Heavy Amphibious Tank						(TODO)
	-- KAL 0303	T3 Heavy AA Tank								(TODO)
	-- KAS 0301	T3 Dreadnought									(IOWA Class)
	-- KAB 2305	T3 Close-In-Weapon-System						(TODO)
	-- KAS 0305	T3 Naval Mothership								(TODO)
	-- KAS 0201	T2 Tech 2 Missile Ship							(TODO)
	-- KAB 2201	T2 Point Defense								(Ascender)
	-- KAB 2202	T2 Mortar Installation							(Holy rain)	-- Slight buff
	-- KAL 0203	T2 Mobile Intel Generator						(TODO)
	-- KAL 0201	T2 Mobile APC									(TODO)
	-- -- KAL 0205	T2 HeavyTankUP									(N/A)
	-- KAL 0202	T2 Heavy Tank Destroyer							(TODO)
	-- KAL 0204	T2 Heavy Beam Tank								(TODO)
	-- -- KAL 0101	Tl HeavyTank									(N/A)
	-- KAA 0101	Tl AA Gunship									(TODO)
	
	-- ------------------------------------------------------------------------------------
	-- 								-- Cybran --
	-- ------------------------------------------------------------------------------------
	
	-- KRS 0304	T4 Naval Mainframe								(TODO)
	-- KRL 0401	T4 Super Heavy Rapid Fire Cannon				(TODO)
	-- KRL 0406	T4 Super Heavy Armored Hovercraft				(TODO)
	-- KRL 0407	T4 Mobile Tank									(Diablo)
	-- -- KRA 0401	T4 Gunship										(N/A)
	-- -- KRL 0404	T4 Assault Vehicle								(N/A)
	-- -- KRL 0402	T4 Assault Bot									(N/A)
	-- KRL 0402	T4 Assault Bot									(Homing Spider)	-- Rebalance
	-- KRL 0308	T3 EMP Cannon									(TODO)
	-- KRA 0301	T3 EMP Bomber									(TODO)
	-- KRL 0302	T3 Mobile Heavy Tank							(Overlord)
	-- KRL 0305	T3 Mobile Combined Defense Platform				(TODO)
	-- KRB 2303	T3 Burst Laser Point Defense					(TODO)
	-- KRL 0301	T3 Main Battle Tank								(Jody)
	-- KRL 0304	T3 MLRS											(Mars)
	-- KRB 2302	T3 Intercontinental Ballistic Missile Launcher	(TODO)
	-- KRL 0307	T3 Mobile EMP Ray								(TODO)
	-- KRB 2301	T3 Heavy Naval Artillery Bunker					(Naval Cannon)
	-- KRS 0302	T3 Heavy Destroyer								(Sadam Class)
	-- KRS 0401	T3 Heavy Cruiser								(Lockdown Class)
	-- -- KRB 2304	T3 Heavy Anti-Air SAM Launcher					(N/A) - Cut Content
	-- -- KRL 0306	T3 Heavy Amphibious Tank						(N/A)
	-- KRL 0303	T3 Heavy AA Tank								(TODO)
	-- KRS 0301	T3 Submersible Dreadnought						(Universe)
	-- KRB 2305	T3 Close-In-Weapon-System						(TODO)
	-- KRS 0305	T3 Heavy Naval Armored Stealth Field			(TODO)
	-- KRS 0201	T2 Subsurface Anti Air Launcher					(TODO)
	-- KRB 2201	T2 Point Defense								(Orthros)
	-- KRB 2202	T2 Reclaiming Facility							(Recycler)
	-- KRL 0203	T2 Mobile Intel Generator						(TODO)
	-- KRL 0201	T2 Mobile APC									(TODO)
	-- -- KRL 0205	T2 HeavyTankUP									(N/A)
	-- KRL 0202	T2 Mobile Artillery								(TODO)
	-- KRL 0204	T2 Mobile Repair Bot							(TODO)
	-- -- KRL 0101	Tl HeavyTank									(N/A)
	-- -- KRA 0101	Tl Gunship										(N/A)
	
	-- ------------------------------------------------------------------------------------
	-- 								-- Seraphim --
	-- ------------------------------------------------------------------------------------
	
	-- KSS 0304	T4 Resonance Field Generator					(TODO)
	-- KSL 0401	T4 Heavy Rocket Tank							(hea fiu)	-- Rebalance
	-- -- KSL 0406	T4 Super Heavy Armored Hovercraft				(N/A)
	-- KSL 0407	T4 Heavy Amphibious Tank						(TODO)
	-- KSA 0401	T4 Gunship										(Vulthoum)	-- Rebalance
	-- KSL 0404	T4 Assault Vehicle								(TODO)
	-- -- KSL 0402	T4 Assault Bot									(TODO)
	-- KSL 0405	T4 Assault Bot									(TODO)
	-- KSL 0308	T3 Resonance Cannon								(TODO)
	-- KSA 0301	T3 Resonance Bomber								(TODO)
	-- KSL 0302	T3 Mobile Heavy Cannon							(TODO)
	-- -- KSL 0305	T3 Mobile Combined Defense Platform				(N/A)
	-- KSB 2303	T3 Chain Lightning Point Defense				(TODO) -- spawn temporary unit with 4 minimum range so that it wont attack the original unit
	-- KSL 0301	T3 Main Battle Tank								(Juun tzu)
	-- KSL 0304	T3 MLRS											(TODO)
	-- KSB 2302	T3 Interdimensional Ballistic Missile Launcher	(TODO)
	-- -- KSL 0307	T3 Hybrid Sniper Missile Launcher				(N/A)
	-- KSB 2301	T3 Heavy Naval Artillery Bunker					(Haratham)
	-- KSS 0302	T3 Heavy Destroyer								(Uan shal voh)
	-- KSS 0401	T3 Heavy Cruiser								(TODO)
	-- -- KSB 2304	T3 Heavy Anti-Air SAM Launcher					(N/A) - Cut Content
	-- KSL 0306	T3 Heavy Amphibious Tank						(TODO)
	-- KSL 0303	T3 Heavy AA Tank								(TODO)
	-- KSS 0301	T3 Dreadnought									(TODO)
	-- KSB 2305	T3 Lightning AA Tower							(TODO)
	-- KSS 0305	T3 Naval Nuke Carrier							(TODO)
	-- KSS 0201	T2 Aircraft Carrier								(TODO)
	-- KSB 2201	T2 Point Defense								(Umuushal)
	-- KSB 2202	T2 Mortar Installation							(TODO)
	-- KSL 0203	T2 Stealth Land Scout							(TODO)
	-- KSL 0201	T2 Mobile APC									(Aranuhn)	-- Rebalance
	-- -- KSL 0205	T2 HeavyTankUP									(N/A)
	-- KSL 0202	T2 Heavy Tank									(TODO)
	-- -- KSL 0204	T2 Heavy Beam Tank								(N/A)
	-- -- KSL 0101	Tl HeavyTank									(N/A)
	-- KSA 0101	Tl Gunship										(TODO)
	
	-- ------------------------------------------------------------------------------------
	-- 								-- Nomads -- not planned as of now
	-- ------------------------------------------------------------------------------------
	
	-- KNS 0304	T4 Support Dreadnought							(TODO)
	-- KNL 0401	T4 Super Heavy Bombardment Tank					(TODO)
	-- KNL 0406	T4 Super Heavy Armored Hovercraft				(TODO)
	-- KNL 0407	T4 Heavy Tank									(TODO)
	-- KNA 0401	T4 Gunship										(TODO)
	-- KNL 0404	T4 Assault Vehicle								(TODO)
	-- KNL 0402	T4 Assault Bot									(TODO)
	-- KNL 0405	T4 Assault Bot									(TODO)
	-- KNL 0308	T3 Nuclear Cannon								(TODO)
	-- KNA 0301	T3 Nuclear Bomber								(TODO)
	-- KNL 0302	T3 Mobile Heavy Cannon							(TODO)
	-- KNL 0305	T3 Mobile Combined Defense Platform				(TODO)
	-- KNB 2303	T3 Missile Point Defense						(TODO)
	-- KNL 0301	T3 Main Battle Tank								(TODO)
	-- KNL 0304	T3 MLRS											(TODO)
	-- KNB 2302	T3 Intercontinental Ballistic Missile Launcher	(TODO)
	-- KNL 0307	T3 Hybrid Sniper Missile Launcher				(TODO)
	-- KNB 2301	T3 Heavy Naval Artillery Bunker					(TODO)
	-- KNS 0302	T3 Heavy Destroyer								(TODO)
	-- KNS 0401	T3 Heavy Cruiser								(TODO)
	-- KNB 2304	T3 Heavy Anti-Air SAM Launcher					(TODO)
	-- KNL 0306	T3 Heavy Amphibious Tank						(TODO)
	-- KNL 0303	T3 Heavy AA Tank								(TODO)
	-- KNS 0301	T3 Dreadnought									(TODO)
	-- KNB 2305	T3 Close-In-Weapon-System						(TODO)
	-- KNS 0305	T3 Battlecarrier								(TODO)
	-- KNS 0201	T2 Tech 2 Early Battleship						(TODO)
	-- KNB 2201	T2 Point Defense								(TODO)
	-- KNB 2202	T2 Mortar Installation							(TODO)
	-- KNL 0203	T2 Mobile Intel Generator						(TODO)
	-- KNL 0201	T2 Mobile APC									(TODO)
	-- -- KNL 0205	T2 HeavyTankUP									(N/A)
	-- KNL 0202	T2 Heavy Tank Destroyer							(TODO)
	-- KNL 0204	T2 Heavy Beam Tank								(TODO)
	-- -- KNL 0101	Tl HeavyTank									(N/A)
	-- KNA 0101	Tl Gunship										(TODO)